r"""
docs/daily_log/_build_index.py
==============================
Regenerate ``docs/daily_log/INDEX.md`` from the log files themselves.

The daily logs are filed in ``MM_YYYY`` folders (``07_2026``) and named
``YYYY-MM-DD_slug.md``.  This script walks those folders, reads each file's
first level-1 heading as its title, and writes a month-grouped index with
newest entries first.

Run from anywhere::

    python docs\daily_log\_build_index.py

It is idempotent and takes no arguments.  ``INDEX.md`` is generated output --
edit the logs or this script, not the index.
"""

from __future__ import annotations

import re
from pathlib import Path

LOG_ROOT = Path(__file__).resolve().parent
INDEX_PATH = LOG_ROOT / "INDEX.md"

#: ``MM_YYYY`` month folders.
MONTH_DIR = re.compile(r"^(?P<m>\d{2})_(?P<y>\d{4})$")
#: ``YYYY-MM-DD_slug.md`` log files.
LOG_FILE = re.compile(r"^(?P<date>\d{4}-\d{2}-\d{2})[_.](?P<slug>.*)\.md$")

MONTH_NAMES = {
    "01": "January", "02": "February", "03": "March", "04": "April",
    "05": "May", "06": "June", "07": "July", "08": "August",
    "09": "September", "10": "October", "11": "November", "12": "December",
}


def first_heading(path: Path) -> str:
    """The file's first ``# `` heading, or a slug-derived fallback."""
    try:
        text = path.read_text(encoding="utf-8")
    except (UnicodeDecodeError, OSError):
        text = ""
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("# "):
            # Drop a leading date that duplicates the filename's own date
            # column, plus the em/en-dash that usually follows it.
            title = stripped[2:].strip()
            title = re.sub(r"^\d{4}-\d{2}-\d{2}\s*[-–—:]?\s*", "", title)
            return title or path.stem
    match = LOG_FILE.match(path.name)
    slug = match["slug"] if match else path.stem
    return slug.replace("_", " ")


def main() -> None:
    months: dict[str, list[tuple[str, str, str]]] = {}
    for month_dir in sorted(LOG_ROOT.iterdir(), reverse=True):
        if not month_dir.is_dir() or not MONTH_DIR.match(month_dir.name):
            continue
        entries: list[tuple[str, str, str]] = []
        for log in sorted(month_dir.glob("*.md"), reverse=True):
            match = LOG_FILE.match(log.name)
            if match is None:
                continue
            entries.append(
                (match["date"], first_heading(log), f"{month_dir.name}/{log.name}")
            )
        if entries:
            months[month_dir.name] = entries

    total = sum(len(v) for v in months.values())
    lines: list[str] = [
        "# Daily log index",
        "",
        "Generated by `docs/daily_log/_build_index.py` — do not edit by hand.",
        "",
        f"{total} entries across {len(months)} month(s), newest first. "
        "Logs are filed in `MM_YYYY` folders.",
        "",
    ]
    for folder, entries in months.items():
        match = MONTH_DIR.match(folder)
        assert match is not None
        heading = f"{MONTH_NAMES[match['m']]} {match['y']}"
        lines += [
            f"## {heading} (`{folder}/`) — {len(entries)} entries",
            "",
            "| Date | Entry |",
            "|---|---|",
        ]
        for date, title, rel in entries:
            safe_title = title.replace("|", r"\|")
            lines.append(f"| {date} | [{safe_title}]({rel}) |")
        lines.append("")

    INDEX_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {INDEX_PATH.relative_to(LOG_ROOT.parents[1])}: "
          f"{total} entries, {len(months)} month(s)")


if __name__ == "__main__":
    main()
