"""The §9.3 selected weight design, reproduced rather than retyped.

Both §9.1 closed-loop experiments (`ch_9_1_ts_period_sweep`, the `T_TS` sweep,
and `ch_9_1_ninner_isolated_sts`, the isolated-STS `N_inner` measurement) must
run at the weights the chapter selects. ``N_inner`` is a joint property of the
period ratio and of ``G_w``: run it at the file defaults of
``experiments/run_multi_system_ofo.py`` (``g_w_der=10``, ``g_w_dso_der=1000``,
...) and the answer describes the *old in-service* controller, not the one
Chapter 9 designs.

The design is therefore rebuilt through the campaign's own recipe --
``load_config_yaml`` -> ``design_payload`` -> ``build_config``
(``tuning_mc/stage_1_search.py::evaluate_one``) -- so that a later correction to
Stage 0 or to the config overlay propagates here instead of leaving a stale
literal behind. The designed weights are then asserted against the archived
evaluation JSON, and a mismatch raises: silently running at *almost* the
selected point is the failure this module exists to prevent.

Selected candidate: ``results/tuning_mc/stage1``, key ``fe010aa3ead1`` --
the FINAL tuning optimum (``rho_emp_p95 = 1.3788``).

*Corrected 2026-08-20.* This module previously named ``campaign_0815`` /
``aa4f6d4a8654`` (``rho_emp_p95 = 1.4480``), the candidate whose coordinates
match the Sec. 9.3 chapter text as drafted. That is a superseded point: the
tuning continued past it. Measuring ``N_inner`` at superseded weights answers
for a controller that will not be used, so both B experiments are re-run here.

The final candidate carries a seventh coordinate, ``dso_v_authority = 20.0``,
which the earlier one did not. It is NOT a stored weight: ``build_config``
turns it into a per-area voltage relief on the spread-limited areas via
``apply_dso_v_relief``, raising ``dso_g_v`` and ``g_w_dso_oltc`` together by
that factor so the OLTC loop gain ``dso_g_v / g_w_dso_oltc`` -- the ratio that
keeps the integer tap out of a limit cycle -- is preserved. The archive
therefore stores ``zone_g_w_class: null`` while the effective config carries
``DSO_2``/``DSO_4`` values at 20x the globals. Both are asserted below, because
a silently unapplied relief would look exactly like a correctly applied one in
the weight comparison.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, Tuple

REPO_ROOT = Path(__file__).resolve().parents[2]

#: Campaign directory and candidate. Named once, here.
CAMPAIGN = "stage1"
CANDIDATE_KEY = "fe010aa3ead1"

#: The seven search coordinates, verbatim from
#: ``results/tuning_mc/stage1/evals/spec_fe010aa3ead1.json``.
KNOBS: Dict[str, float] = {
    "lambda_tso": 0.17827533411555277,
    "lambda_dso": 1.7957360834719915,
    "tau": 0.7079457843841379,
    "engage_tso_pu": 0.015,
    "engage_dso_pu": 0.04988155787422199,
    "dso_g_v_ratio": 0.8413951416451951,
    "dso_v_authority": 20.0,
}

#: Areas the ``dso_v_authority`` relief applies to, and the factor. Asserted
#: against the built config rather than trusted: the relief is generated by
#: ``apply_dso_v_relief`` at build time, not stored in the archive, so a
#: version that stopped applying it would still pass a weights-only check.
RELIEF_AREAS = ("DSO_2", "DSO_4")

#: Relative tolerance on the weight assertion. The recipe is deterministic, so
#: this is a float-repr guard, not a tolerance band: anything larger than this
#: means the design changed and the run must not proceed.
WEIGHT_RTOL = 1e-9

_EVAL_DIR = REPO_ROOT / "results" / "tuning_mc" / CAMPAIGN / "evals"
_DESIGN_DIR = REPO_ROOT / "results" / "tuning_mc" / CAMPAIGN / "designs"


def archived_evaluation() -> Dict[str, Any]:
    """The Tier-1 evaluation record of the selected candidate."""
    path = _EVAL_DIR / f"tier1_{CANDIDATE_KEY}.json"
    if not path.exists():
        raise FileNotFoundError(
            f"archived evaluation missing: {path}. The selected design cannot "
            f"be verified, so the run is refused rather than executed against "
            f"an unchecked config.")
    return json.loads(path.read_text(encoding="utf-8-sig"))


def build_selected_config() -> Tuple[Any, Dict[str, Any]]:
    """``(cfg, provenance)`` at the §9.3 selected weights.

    Raises if the rebuilt weights differ from the archived ones, or if the
    knobs in the archive differ from :data:`KNOBS` -- either means this module
    is describing a different candidate from the one it names.
    """
    import sys
    if str(REPO_ROOT) not in sys.path:
        sys.path.insert(0, str(REPO_ROOT))

    from tuning._io import load_config_yaml
    from tuning_mc.stage_1_search import (
        APPLIED_FIELDS, DEFAULT_BASELINE, build_config, design_payload,
        knob_key, stage0_fingerprint, _zone_lambda_spec,
    )

    archive = archived_evaluation()

    # (1) The archive must be the candidate this module claims.
    if knob_key(KNOBS) != CANDIDATE_KEY:
        raise AssertionError(
            f"knob_key(KNOBS) = {knob_key(KNOBS)!r} but this module names "
            f"{CANDIDATE_KEY!r}; the coordinates and the key disagree.")
    for field, want in KNOBS.items():
        got = float(archive["knobs"][field])
        if abs(got - want) > 1e-12:
            raise AssertionError(
                f"knob {field}: archive has {got!r}, this module has {want!r}")

    # (2) Rebuild through the campaign's own recipe.
    baseline_cfg = load_config_yaml(Path(DEFAULT_BASELINE))
    payload = design_payload(KNOBS, baseline=Path(DEFAULT_BASELINE),
                             design_scenario="none", workdir=_DESIGN_DIR)
    block = payload["config_block"]
    weights = {f: float(block[f]["designed"]) for f in APPLIED_FIELDS}

    # zone_g_w_class is null for this candidate: global scalars, no per-area
    # block. Recomputed rather than assumed, so a change of knobs is caught.
    zblock = None
    if _zone_lambda_spec(KNOBS) is not None:
        raise AssertionError(
            "this candidate carries a per-zone lambda spec, but the archived "
            "zone_g_w_class is null; the two cannot both be right.")
    if archive.get("zone_g_w_class") is not None:
        raise AssertionError(
            f"archive zone_g_w_class is {archive['zone_g_w_class']!r}, "
            f"expected null for this candidate.")

    # (3) The assertion the handoff asks for: designed == archived.
    mismatches = []
    for field, got in sorted(weights.items()):
        want = float(archive["weights"][field])
        if want == 0.0:
            ok = got == 0.0
        else:
            ok = abs(got - want) <= WEIGHT_RTOL * abs(want)
        if not ok:
            mismatches.append(f"  {field}: rebuilt {got!r} != archived {want!r}")
    if mismatches:
        raise AssertionError(
            "the rebuilt design does not reproduce the archived one -- Stage 0 "
            "or the config overlay has changed since campaign_0815, so this "
            "run would NOT be at the weights the chapter selects:\n"
            + "\n".join(mismatches))

    cfg = build_config(KNOBS, weights, baseline_cfg, zone_g_w_class=zblock)

    # (4) dso_g_v is set by the overlay from the searched ratio, not designed
    # by Stage 0, so it is checked against the archive separately.
    want_gv = float(archive["dso_g_v"])
    got_gv = float(cfg.dso_g_v)
    if abs(got_gv - want_gv) > WEIGHT_RTOL * abs(want_gv):
        raise AssertionError(
            f"dso_g_v: built {got_gv!r} != archived {want_gv!r}")

    # (5) The per-area relief. Generated, not stored, so it is checked against
    # the arithmetic it is defined by: dso_g_v and g_w_dso_oltc both scaled by
    # dso_v_authority on the spread-limited areas, which preserves the OLTC
    # loop gain dso_g_v / g_w_dso_oltc.
    relief = {}
    factor = KNOBS.get("dso_v_authority")
    if factor is not None:
        per_area_gv = dict(getattr(cfg, "dso_g_v_per_area", {}) or {})
        # dso_g_w_class, NOT zone_g_w_class: apply_dso_v_relief writes the
        # per-area OLTC weight into the former. The two names are one letter
        # apart in intent and completely different in effect -- reading the
        # wrong one reported the relief as absent when it had applied.
        per_area_cls = dict(getattr(cfg, "dso_g_w_class", {}) or {})
        missing = [a for a in RELIEF_AREAS if a not in per_area_gv]
        if missing:
            raise AssertionError(
                f"dso_v_authority = {factor} is set, but the built config has "
                f"no per-area dso_g_v for {missing}. The relief did not apply; "
                f"a weights-only check would not have caught this.")
        for area in RELIEF_AREAS:
            want = got_gv * float(factor)
            got = float(per_area_gv[area])
            if abs(got - want) > 1e-6 * abs(want):
                raise AssertionError(
                    f"{area} dso_g_v: built {got!r} != {got_gv!r} * {factor!r} "
                    f"= {want!r}")
        # The OLTC half must scale by the same factor, or the loop gain
        # dso_g_v / g_w_dso_oltc moves and the integer tap limit-cycles
        # (measured 2026-08-18: 50.5 reversals/h at factor 6.7).
        want_oltc = float(cfg.g_w_dso_oltc) * float(factor)
        for area in RELIEF_AREAS:
            got_oltc = float((per_area_cls.get(area) or {}).get("dso_oltc",
                                                                float("nan")))
            if not abs(got_oltc - want_oltc) <= 1e-6 * abs(want_oltc):
                raise AssertionError(
                    f"{area} dso_oltc: built {got_oltc!r} != "
                    f"{cfg.g_w_dso_oltc!r} * {factor!r} = {want_oltc!r}; the "
                    f"OLTC half of the relief did not apply, so the loop gain "
                    f"dso_g_v / g_w_dso_oltc has moved")
        relief = {"dso_g_v_per_area": {a: float(per_area_gv[a])
                                       for a in RELIEF_AREAS},
                  "dso_g_w_class": {a: per_area_cls.get(a)
                                    for a in RELIEF_AREAS},
                  "factor": float(factor)}

    provenance = {
        "campaign": CAMPAIGN,
        "candidate_key": CANDIDATE_KEY,
        "knobs": dict(KNOBS),
        "weights": weights,
        "dso_g_v": got_gv,
        "zone_g_w_class": None,
        "per_area_relief": relief,
        "baseline_yaml": str(DEFAULT_BASELINE),
        "stage0_fingerprint": stage0_fingerprint(),
        "design_payload": str(_DESIGN_DIR / f"stage0_{CANDIDATE_KEY}.json"),
        "archived_eval": str(_EVAL_DIR / f"tier1_{CANDIDATE_KEY}.json"),
        "archived_rho_emp_p95": archive.get("worst_rho_emp_p95"),
        "verified": "rebuilt weights == archived weights",
    }
    return cfg, provenance


if __name__ == "__main__":
    cfg, prov = build_selected_config()
    print(json.dumps(prov, indent=2, default=str))
    print(f"\ntso_period_s={cfg.tso_period_s} dso_period_s={cfg.dso_period_s} "
          f"dt_s={cfg.dt_s} scenario={cfg.scenario} "
          f"precondition_g_w={cfg.precondition_g_w}")
